{{- if and .Values.bankapp.ingress .Values.bankapp.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-bankapp-ingress
  annotations:
{{- range $key, $value := .Values.bankapp.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
{{- end }}
spec:
  ingressClassName: {{ .Values.bankapp.ingress.className }}
  rules:
{{- range .Values.bankapp.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bankapp-service
                port:
                  number: {{ $.Values.bankapp.service.port }}
{{- end }}
{{- end }}

